### ISSUE TITLE
Timeout on createDevice: no wait parameter

### ISSUE THREAD

**Issue by philpownall** [futomi/node-lifx-lan#18]
In a busy (32 devices) environment on a slow machine (a raspberry pi 3), I am seeing Timeout errors on createDevice (see below).  When the LIFX is run in a non-busy environment (ie in the test module, where the only device is the LIFX bulb), no Timeout errors are encountered - but there is no wait parameter on the createDevice call (like the wait parameter on the Discover method) - is it possible to adjust the Timeout without calling Discover?

createDevice error Error: Timeout
    at Timeout.setTimeout [as _onTimeout] (/home/pi/MyHouse/node_modules/node-lifx-lan/lib/lifx-lan-udp.js:127:12)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

**Comment by philpownall** [comment]
An update: it turns out that this is an issue with the Raspberry Pi automatically powering down its WiFi interface, resulting in Timeouts on transfers that try to wake it up and do not get a response within the timeout interval.  To resolve, I prevented the Pi from powering down the Wifi, and the timeouts disappeared.
