### ISSUE TITLE
Repeat Discover Error - "Error: send EACCES "

### ISSUE THREAD

**Issue by Xeonzinc** [futomi/node-lifx-lan#34]
Hi,

When running my initial discovery of LIFX bulbs this library always works perfectly, however on the second check (test at both 1m and 10m later), it consistently causes the following error and never returns the object of devices. My bulbs are not on 255.

```
Error: send EACCES 192.168.0.255:56700
    at doSend (dgram.js:683:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:313:12)
    at afterDns (dgram.js:629:5)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
    at runNextTicks (internal/process/task_queues.js:66:3)
    at processTimers (internal/timers.js:489:9) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'send',
  address: '192.168.0.255',
  port: 56700
}
```

Does anyone have any suggestions what may be causing this?

**Comment by Xeonzinc** [comment]
After a little more investigation it turns out the issue only occurred when running lifx.discovery alongside regular lifx.setColorFilter updates to the bulb. Some overlap between the functions must have caused the error. My workaround has been to pause updates via setColorFilter while the discovery function is running, although it doesn't quite solve the problem as this introduces a period where the lights are static.

---

Update - This doesn't seems to have solved it, the issue now seems to occur even when it didn't before.
