### ISSUE TITLE
Multiple cresteDevice even after destroy.

### ISSUE THREAD

**Issue by MarcGodard** [futomi/node-lifx-lan#6]
If you do:

```
Lifx.createDevice({
      mac: context.result.mac,
      ip: context.result.host
    })
    .then(device => {
        device.turnOn()
    })
    .then(() => {
        Lifx.destroy()
    })
```

Twice, not at the same time, you get the following error.

```
info: Feathers application started on http://localhost:3030
/Users/marcgodard/GitHub/remote-api/node_modules/node-lifx-lan/lib/lifx-lan-udp.js:37
				this._udp.unref()
				          ^

TypeError: Cannot read property 'unref' of null
    at Socket._udp.close (/Users/marcgodard/GitHub/remote-api/node_modules/node-lifx-lan/lib/lifx-lan-udp.js:37:15)
    at Socket.emit (events.js:185:15)
    at socketCloseNT (dgram.js:527:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
```

Possibly the destroy doesn't work if you used createDevice ?

Here is another stack trace:

```
TypeError: Cannot read property 'unref' of null
    at Promise (/Users/marcgodard/GitHub/remote-api/node_modules/node-lifx-lan/lib/lifx-lan-udp.js:42:14)
    at new Promise (<anonymous>)
    at LifxLanUdp.destroy (/Users/marcgodard/GitHub/remote-api/node_modules/node-lifx-lan/lib/lifx-lan-udp.js:34:16)
    at Promise (/Users/marcgodard/GitHub/remote-api/node_modules/node-lifx-lan/lib/lifx-lan.js:886:12)
    at new Promise (<anonymous>)
    at LifxLan.destroy (/Users/marcgodard/GitHub/remote-api/node_modules/node-lifx-lan/lib/lifx-lan.js:885:16)
    at lifxkService.patch.then.completeObj (/Users/marcgodard/GitHub/remote-api/src/services/lifx/lifx-status.js:44:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
```

**Comment by MarcGodard** [comment]
My bad...

**Comment by futomi** [comment]
Never mind. Thank you for your feedback.
Though you have already found what's wrong in your sample code, here is a correct code:

```javascript
Lifx.createDevice({
  mac: 'D0:73:D5:25:36:B0',
  ip: '192.168.11.32'
}).then((dev) => {
  return dev.turnOn();
}).then(() => {
  return Lifx.destroy(); // Here is important. The destroy() method returns a Promise object.
}).then(() => {
  console.log('Done');
}).catch((error) => {
  console.error(error);
});
```
